name: YAML Lint

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".github/workflows/yaml-lint.yml"
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  yaml-lint:
    uses: actionsforge/actions/.github/workflows/yaml-lint.yml@main
